# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/xiang/ml_ann/ann_tools_eric/anntools.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QColor, QBrush, QPainter, QPen, QPalette
from PyQt5.QtCore import Qt
import math
from PyQt5.QtWidgets import QWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(977, 562)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fileListView = QtWidgets.QListView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileListView.sizePolicy().hasHeightForWidth())
        self.fileListView.setSizePolicy(sizePolicy)
        self.fileListView.setBaseSize(QtCore.QSize(0, 0))
        self.fileListView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fileListView.setObjectName("fileListView")
        self.verticalLayout_6.addWidget(self.fileListView)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rootPathLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.rootPathLineEdit.setReadOnly(True)
        self.rootPathLineEdit.setObjectName("rootPathLineEdit")
        self.horizontalLayout.addWidget(self.rootPathLineEdit)
        self.rootPathSelButton = QtWidgets.QPushButton(self.centralWidget)
        self.rootPathSelButton.setObjectName("rootPathSelButton")
        self.horizontalLayout.addWidget(self.rootPathSelButton)
        self.fileNameLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileNameLineEdit.sizePolicy().hasHeightForWidth())
        self.fileNameLineEdit.setSizePolicy(sizePolicy)
        self.fileNameLineEdit.setText("")
        self.fileNameLineEdit.setObjectName("fileNameLineEdit")
        self.horizontalLayout.addWidget(self.fileNameLineEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.prevPushBtn = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevPushBtn.sizePolicy().hasHeightForWidth())
        self.prevPushBtn.setSizePolicy(sizePolicy)
        self.prevPushBtn.setObjectName("prevPushBtn")
        self.horizontalLayout_10.addWidget(self.prevPushBtn)
        self.nextPushBtn = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextPushBtn.sizePolicy().hasHeightForWidth())
        self.nextPushBtn.setSizePolicy(sizePolicy)
        self.nextPushBtn.setObjectName("nextPushBtn")
        self.horizontalLayout_10.addWidget(self.nextPushBtn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.prevPlainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevPlainTextEdit.sizePolicy().hasHeightForWidth())
        self.prevPlainTextEdit.setSizePolicy(sizePolicy)
        self.prevPlainTextEdit.setReadOnly(True)
        self.prevPlainTextEdit.setObjectName("prevPlainTextEdit")
        self.horizontalLayout_5.addWidget(self.prevPlainTextEdit)
        self.currPlainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currPlainTextEdit.sizePolicy().hasHeightForWidth())
        self.currPlainTextEdit.setSizePolicy(sizePolicy)
        self.currPlainTextEdit.setReadOnly(True)
        self.currPlainTextEdit.setObjectName("currPlainTextEdit")
        self.horizontalLayout_5.addWidget(self.currPlainTextEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prevGraphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.prevGraphicsView.setObjectName("prevGraphicsView")
        self.horizontalLayout_2.addWidget(self.prevGraphicsView)
        self.currGraphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.currGraphicsView.setObjectName("currGraphicsView")
        self.horizontalLayout_2.addWidget(self.currGraphicsView)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.fileListView.raise_()
        self.fileListView.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ann Tools"))
        self.rootPathLineEdit.setText(_translate("MainWindow", "Select root path of dataset"))
        self.rootPathSelButton.setText(_translate("MainWindow", "Select"))
        self.rootPathSelButton.setShortcut(_translate("MainWindow", "O"))
        self.prevPushBtn.setText(_translate("MainWindow", "Previous"))
        self.prevPushBtn.setShortcut(_translate("MainWindow", "A"))
        self.nextPushBtn.setText(_translate("MainWindow", "Next"))
        self.nextPushBtn.setShortcut(_translate("MainWindow", "D"))
        self.label_2.setText(_translate("MainWindow", "Previous Image:"))
        self.label.setText(_translate("MainWindow", "Current Image:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

