# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 562)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.prevPlainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevPlainTextEdit.sizePolicy().hasHeightForWidth())
        self.prevPlainTextEdit.setSizePolicy(sizePolicy)
        self.prevPlainTextEdit.setReadOnly(True)
        self.prevPlainTextEdit.setObjectName("prevPlainTextEdit")
        self.horizontalLayout_5.addWidget(self.prevPlainTextEdit)
        self.currPlainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currPlainTextEdit.sizePolicy().hasHeightForWidth())
        self.currPlainTextEdit.setSizePolicy(sizePolicy)
        self.currPlainTextEdit.setReadOnly(True)
        self.currPlainTextEdit.setObjectName("currPlainTextEdit")
        self.horizontalLayout_5.addWidget(self.currPlainTextEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rootPathLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.rootPathLineEdit.setReadOnly(True)
        self.rootPathLineEdit.setObjectName("rootPathLineEdit")
        self.horizontalLayout.addWidget(self.rootPathLineEdit)
        self.rootPathSelButton = QtWidgets.QPushButton(self.centralWidget)
        self.rootPathSelButton.setObjectName("rootPathSelButton")
        self.horizontalLayout.addWidget(self.rootPathSelButton)
        self.fileNameLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileNameLineEdit.sizePolicy().hasHeightForWidth())
        self.fileNameLineEdit.setSizePolicy(sizePolicy)
        self.fileNameLineEdit.setText("")
        self.fileNameLineEdit.setObjectName("fileNameLineEdit")
        self.horizontalLayout.addWidget(self.fileNameLineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prevGraphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.prevGraphicsView.setObjectName("prevGraphicsView")
        self.horizontalLayout_2.addWidget(self.prevGraphicsView)
        self.currGraphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.currGraphicsView.setObjectName("currGraphicsView")
        self.horizontalLayout_2.addWidget(self.currGraphicsView)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.prevPushBtn = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevPushBtn.sizePolicy().hasHeightForWidth())
        self.prevPushBtn.setSizePolicy(sizePolicy)
        self.prevPushBtn.setObjectName("prevPushBtn")
        self.horizontalLayout_10.addWidget(self.prevPushBtn)
        self.nextPushBtn = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextPushBtn.sizePolicy().hasHeightForWidth())
        self.nextPushBtn.setSizePolicy(sizePolicy)
        self.nextPushBtn.setObjectName("nextPushBtn")
        self.horizontalLayout_10.addWidget(self.nextPushBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ann Tools"))
        self.rootPathLineEdit.setText(_translate("MainWindow", "Select root path of dataset"))
        self.rootPathSelButton.setText(_translate("MainWindow", "Select"))
        self.rootPathSelButton.setShortcut(_translate("MainWindow", "O"))
        self.label_2.setText(_translate("MainWindow", "Previous Image:"))
        self.label.setText(_translate("MainWindow", "Current Image:"))
        self.prevPushBtn.setText(_translate("MainWindow", "Previous"))
        self.prevPushBtn.setShortcut(_translate("MainWindow", "A"))
        self.nextPushBtn.setText(_translate("MainWindow", "Next"))
        self.nextPushBtn.setShortcut(_translate("MainWindow", "D"))

